api_version = "2025-04"

[[extensions]]
name = "shipping-delay-message"
handle = "shipping-delay-message"
type = "ui_extension"

  [[extensions.targeting]]
  module = "./src/Checkout.jsx"
  target = "purchase.checkout.block.render"

  [extensions.capabilities]
  api_access = true

  [[extensions.metafields]]
  namespace = "custom"
  key = "shipping_delay_message"
